package br.com.estatistica.visao;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.LayoutStyle.ComponentPlacement;

@SuppressWarnings("serial")
public class FormQuestionarioCoeficienteArgumentacao extends JFrame {

	/**
	 * Creates new form FormQuestionarioCoeficienteArgumentacao
	 */
	public FormQuestionarioCoeficienteArgumentacao() {
		setResizable(false);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING:
	 * Do NOT modify this code. The content of this method is always regenerated by the
	 * Form Editor.
	 */
	private void initComponents() {

		defineComponents();

		addActionListenerButtons();

		configuraComponentes();
	}

	private void addActionListenerButtons() {
		btnNovo.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				btnNovoActionPerformed(evt);
			}
		});

		btnSalvar.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent evt) {
				btnSalvarActionPerformed(evt);
			}
		});

		btnExcluir.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				btnExcluirActionPerformed(e);
			}
		});
	}

	protected void btnExcluirActionPerformed(ActionEvent evt) {
		// código para excluir da lista.
	}

	protected void btnSalvarActionPerformed(ActionEvent evt) {
		// código para adicionar a lista
	}

	private void configuraComponentes() {
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Questionario para Coeficiente de Argumentação");

		pnlPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder()));

		jLabel1.setText("Pergunta");

		jLabel2.setText("Resposta");

		buttonGroup1.add(rbAlto);
		rbAlto.setText("Alto");

		buttonGroup1.add(rbMedio);
		rbMedio.setText("Médio");

		buttonGroup1.add(rbBaixo);
		rbBaixo.setText("Baixo");

		jLabel4.setText("Valores");

		jLabel5.setText("Alto:");

		jLabel6.setText("Médio:");

		jLabel7.setText("Baixo:");

		btnNovo.setText("Novo");

		btnExcluir.setText("Excluir");

		btnSalvar.setText("Salvar");

		btnCancelar.setText("Cancelar");

		btnCalcular.setText("Calcular");

		lblResultado.setText("lblResultado");

		javax.swing.GroupLayout pnlPrincipalLayout = createGroupLayout();
		configureGroupLayout(pnlPrincipalLayout);

		setSize(new Dimension(464, 367));
		setLocationRelativeTo(null);
	}

	private void defineComponents() {
		buttonGroup1 = new javax.swing.ButtonGroup();
		pnlPrincipal = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		txtPergunta = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		rbAlto = new javax.swing.JRadioButton();
		rbMedio = new javax.swing.JRadioButton();
		rbBaixo = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		txtValorAlto = new javax.swing.JTextField();
		txtValorMedio = new javax.swing.JTextField();
		txtValorBaixo = new javax.swing.JTextField();
		btnNovo = new javax.swing.JButton();
		btnExcluir = new javax.swing.JButton();
		btnSalvar = new javax.swing.JButton();
		btnCancelar = new javax.swing.JButton();
		spItens = new javax.swing.JScrollPane();

		table = new JTable();
		spItens.setViewportView(table);
		btnCalcular = new javax.swing.JButton();
		lblResultado = new javax.swing.JLabel();
	}

	private void configureGroupLayout(javax.swing.GroupLayout pnlPrincipalLayout) {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(
		        layout.createSequentialGroup().addContainerGap()
		                .addComponent(pnlPrincipal, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		                .addContainerGap(12, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING).addGroup(
		        layout.createSequentialGroup().addContainerGap()
		                .addComponent(pnlPrincipal, GroupLayout.PREFERRED_SIZE, 319, GroupLayout.PREFERRED_SIZE)
		                .addContainerGap(24, Short.MAX_VALUE)));
		getContentPane().setLayout(layout);
	}

	private javax.swing.GroupLayout createGroupLayout() {
		javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
		pnlPrincipalLayout
		        .setHorizontalGroup(pnlPrincipalLayout
		                .createParallelGroup(Alignment.LEADING)
		                .addGroup(
		                        pnlPrincipalLayout
		                                .createSequentialGroup()
		                                .addContainerGap()
		                                .addGroup(
		                                        pnlPrincipalLayout
		                                                .createParallelGroup(Alignment.LEADING)
		                                                .addComponent(jLabel1)
		                                                .addComponent(txtPergunta, 412, 412, 412)
		                                                .addGroup(
		                                                        pnlPrincipalLayout
		                                                                .createSequentialGroup()
		                                                                .addGroup(
		                                                                        pnlPrincipalLayout
		                                                                                .createParallelGroup(Alignment.TRAILING, false)
		                                                                                .addComponent(spItens, GroupLayout.PREFERRED_SIZE,
		                                                                                        412, GroupLayout.PREFERRED_SIZE)
		                                                                                .addGroup(
		                                                                                        Alignment.LEADING,
		                                                                                        pnlPrincipalLayout
		                                                                                                .createSequentialGroup()
		                                                                                                .addGroup(
		                                                                                                        pnlPrincipalLayout
		                                                                                                                .createParallelGroup(
		                                                                                                                        Alignment.LEADING)
		                                                                                                                .addGroup(
		                                                                                                                        pnlPrincipalLayout
		                                                                                                                                .createSequentialGroup()
		                                                                                                                                .addComponent(
		                                                                                                                                        btnNovo,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                                        80,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        btnSalvar,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                                        80,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE))
		                                                                                                                .addComponent(
		                                                                                                                        jLabel2)
		                                                                                                                .addGroup(
		                                                                                                                        pnlPrincipalLayout
		                                                                                                                                .createSequentialGroup()
		                                                                                                                                .addComponent(
		                                                                                                                                        rbAlto)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.UNRELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        rbMedio)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        rbBaixo)))
		                                                                                                .addPreferredGap(
		                                                                                                        ComponentPlacement.RELATED)
		                                                                                                .addGroup(
		                                                                                                        pnlPrincipalLayout
		                                                                                                                .createParallelGroup(
		                                                                                                                        Alignment.LEADING,
		                                                                                                                        false)
		                                                                                                                .addComponent(
		                                                                                                                        btnExcluir,
		                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                        80,
		                                                                                                                        GroupLayout.PREFERRED_SIZE)
		                                                                                                                .addComponent(
		                                                                                                                        jLabel4)
		                                                                                                                .addGroup(
		                                                                                                                        pnlPrincipalLayout
		                                                                                                                                .createSequentialGroup()
		                                                                                                                                .addComponent(
		                                                                                                                                        jLabel5)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        txtValorAlto)))
		                                                                                                .addPreferredGap(
		                                                                                                        ComponentPlacement.RELATED)
		                                                                                                .addGroup(
		                                                                                                        pnlPrincipalLayout
		                                                                                                                .createParallelGroup(
		                                                                                                                        Alignment.TRAILING)
		                                                                                                                .addGroup(
		                                                                                                                        pnlPrincipalLayout
		                                                                                                                                .createSequentialGroup()
		                                                                                                                                .addComponent(
		                                                                                                                                        jLabel6)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        txtValorMedio,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                                        41,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        jLabel7)
		                                                                                                                                .addPreferredGap(
		                                                                                                                                        ComponentPlacement.RELATED)
		                                                                                                                                .addComponent(
		                                                                                                                                        txtValorBaixo,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                                        41,
		                                                                                                                                        GroupLayout.PREFERRED_SIZE))
		                                                                                                                .addComponent(
		                                                                                                                        btnCancelar,
		                                                                                                                        GroupLayout.PREFERRED_SIZE,
		                                                                                                                        80,
		                                                                                                                        GroupLayout.PREFERRED_SIZE)))
		                                                                                .addGroup(
		                                                                                        Alignment.LEADING,
		                                                                                        pnlPrincipalLayout
		                                                                                                .createSequentialGroup()
		                                                                                                .addComponent(btnCalcular)
		                                                                                                .addPreferredGap(
		                                                                                                        ComponentPlacement.RELATED,
		                                                                                                        GroupLayout.DEFAULT_SIZE,
		                                                                                                        Short.MAX_VALUE)
		                                                                                                .addComponent(lblResultado)))
		                                                                .addGap(0, 0, Short.MAX_VALUE))).addContainerGap()));
		pnlPrincipalLayout.setVerticalGroup(pnlPrincipalLayout.createParallelGroup(Alignment.LEADING).addGroup(
		        pnlPrincipalLayout
		                .createSequentialGroup()
		                .addComponent(jLabel1)
		                .addGap(0)
		                .addGroup(
		                        pnlPrincipalLayout
		                                .createParallelGroup(Alignment.TRAILING)
		                                .addGroup(
		                                        pnlPrincipalLayout
		                                                .createSequentialGroup()
		                                                .addComponent(txtPergunta, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE,
		                                                        GroupLayout.PREFERRED_SIZE)
		                                                .addGap(5)
		                                                .addComponent(jLabel2)
		                                                .addPreferredGap(ComponentPlacement.RELATED)
		                                                .addGroup(
		                                                        pnlPrincipalLayout.createParallelGroup(Alignment.BASELINE)
		                                                                .addComponent(rbAlto).addComponent(rbMedio).addComponent(rbBaixo)))
		                                .addGroup(
		                                        pnlPrincipalLayout
		                                                .createSequentialGroup()
		                                                .addComponent(jLabel4)
		                                                .addPreferredGap(ComponentPlacement.RELATED)
		                                                .addGroup(
		                                                        pnlPrincipalLayout
		                                                                .createParallelGroup(Alignment.BASELINE)
		                                                                .addComponent(jLabel5)
		                                                                .addComponent(txtValorAlto, GroupLayout.PREFERRED_SIZE,
		                                                                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		                                                                .addComponent(jLabel6)
		                                                                .addComponent(txtValorMedio, GroupLayout.PREFERRED_SIZE,
		                                                                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
		                                                                .addComponent(jLabel7)
		                                                                .addComponent(txtValorBaixo, GroupLayout.PREFERRED_SIZE,
		                                                                        GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
		                .addPreferredGap(ComponentPlacement.RELATED)
		                .addGroup(
		                        pnlPrincipalLayout.createParallelGroup(Alignment.BASELINE).addComponent(btnSalvar).addComponent(btnExcluir)
		                                .addComponent(btnNovo).addComponent(btnCancelar))
		                .addPreferredGap(ComponentPlacement.RELATED)
		                .addComponent(spItens, GroupLayout.PREFERRED_SIZE, 161, GroupLayout.PREFERRED_SIZE)
		                .addPreferredGap(ComponentPlacement.UNRELATED)
		                .addGroup(
		                        pnlPrincipalLayout.createParallelGroup(Alignment.BASELINE).addComponent(btnCalcular)
		                                .addComponent(lblResultado)).addContainerGap(332, Short.MAX_VALUE)));
		pnlPrincipal.setLayout(pnlPrincipalLayout);
		return pnlPrincipalLayout;
	}

	protected void btnNovoActionPerformed(ActionEvent evt) {
		txtPergunta.setText("");
		txtValorAlto.setText("");
		txtValorBaixo.setText("");
		txtValorMedio.setText("");
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(FormQuestionarioCoeficienteArgumentacao.class.getName()).log(java.util.logging.Level.SEVERE,
			        null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(FormQuestionarioCoeficienteArgumentacao.class.getName()).log(java.util.logging.Level.SEVERE,
			        null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(FormQuestionarioCoeficienteArgumentacao.class.getName()).log(java.util.logging.Level.SEVERE,
			        null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(FormQuestionarioCoeficienteArgumentacao.class.getName()).log(java.util.logging.Level.SEVERE,
			        null, ex);
		}

		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new FormQuestionarioCoeficienteArgumentacao().setVisible(true);
			}
		});
	}

	private javax.swing.JButton btnCalcular;
	private javax.swing.JButton btnCancelar;
	private javax.swing.JButton btnExcluir;
	private javax.swing.JButton btnNovo;
	private javax.swing.JButton btnSalvar;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel lblResultado;
	private javax.swing.JPanel pnlPrincipal;
	private javax.swing.JRadioButton rbAlto;
	private javax.swing.JRadioButton rbBaixo;
	private javax.swing.JRadioButton rbMedio;
	private javax.swing.JScrollPane spItens;
	private javax.swing.JTextField txtPergunta;
	private javax.swing.JTextField txtValorAlto;
	private javax.swing.JTextField txtValorBaixo;
	private javax.swing.JTextField txtValorMedio;
	private JTable table;
}
